### ISSUE TITLE
Serialization of 'pocketmine\block\Opaque' is not allowed

### ISSUE THREAD

**Issue by alvin0319** [alvin0319/Sentry#3]
```
Fatal error: Uncaught Exception: Serialization of 'pocketmine\block\Opaque@anonymous' is not allowed in phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/plugins/Sentry.phar/src/alvin0319/Sentry/SentryThread.php:65
Stack trace:
#0 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/plugins/Sentry.phar/src/alvin0319/Sentry/SentryThread.php(65): igbinary_serialize(Object(pocketmine\utils\AssumptionFailedError))
#1 [internal function]: alvin0319\Sentry\SentryThread->alvin0319\Sentry\{closure}()
#2 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/plugins/Sentry.phar/src/alvin0319/Sentry/SentryThread.php(67): Threaded->synchronized(Object(Closure))
#3 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/plugins/Sentry.phar/src/alvin0319/Sentry/SentryLogger.php(53): alvin0319\Sentry\SentryThread->writeException(Object(pocketmine\utils\AssumptionFailedError))
#4 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/PocketMine-MP.phar/src/Server.php(1515): alvin0319\Sentry\SentryLogger->logException(Object(pocketmine\utils\AssumptionFailedError), Array)
#5 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/PocketMine-MP.phar/src/Server.php(1049): pocketmine\Server->exceptionHandler(Object(pocketmine\utils\AssumptionFailedError))
#6 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/PocketMine-MP.phar/src/PocketMine.php(304): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), 'D:\\D-Backups\\MC...', 'D:\\D-Backups\\MC...')
#7 phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/PocketMine-MP.phar/src/PocketMine.php(327): pocketmine\server()
#8 D:\D-Backups\MCBE\PocketMine-MP-Projects\Neutronia\PocketMine-MP.phar(11): require('phar://D:/D-Bac...')
#9 {main}
  thrown in phar://D:/D-Backups/MCBE/PocketMine-MP-Projects/Neutronia/plugins/Sentry.phar/src/alvin0319/Sentry/SentryThread.php on line 65
```

According to the investigation from Sentry, It seems `Error::getTraces()` contains the list of objects, which caused that. 

Sentry Error: https://sentry.io/share/issue/ea2b81abb2d642e28c7ced8e768822af/

**Comment by alvin0319** [comment]
Closed in https://github.com/alvin0319/Sentry/commit/8e979308550d70dab896edd4aa87979e0cca38e2
